# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\",\n\x0b\x43hatRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t\",\n\x0c\x41gentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0b\n\x03tab\x18\x02 \x01(\t\"3\n\rAgentResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0cjson_payload\x18\x02 \x01(\t\"\x17\n\x07LogLine\x12\x0c\n\x04line\x18\x01 \x01(\t\"\x1d\n\nLogRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"2\n\x0fWorkflowRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"\xae\x01\n\x0b\x41gentUpdate\x12\x1e\n\x03log\x18\x01 \x01(\x0b\x32\x0f.agent.LogEntryH\x00\x12%\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x14.agent.WorkflowEventH\x00\x12$\n\x06\x61nswer\x18\x03 \x01(\x0b\x32\x12.agent.FinalAnswerH\x00\x12\'\n\x08workflow\x18\x04 \x01(\x0b\x32\x13.agent.WorkflowListH\x00\x42\t\n\x07payload\"B\n\x08LogEntry\x12\x12\n\nagent_name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"3\n\rWorkflowEvent\x12\x12\n\nagent_name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1e\n\x0b\x46inalAnswer\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"+\n\x0cWorkflowItem\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\"2\n\x0cWorkflowList\x12\"\n\x05items\x18\x01 \x03(\x0b\x32\x13.agent.WorkflowItem2M\n\x0b\x43hatService\x12>\n\x11SendMessageStream\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponse0\x01\x32\xc6\x01\n\x0c\x41gentService\x12\x39\n\nStreamData\x12\x13.agent.AgentRequest\x1a\x14.agent.AgentResponse0\x01\x12\x39\n\x12StreamLogsFromFile\x12\x11.agent.LogRequest\x1a\x0e.agent.LogLine0\x01\x12@\n\x10RunAgentWorkflow\x12\x16.agent.WorkflowRequest\x1a\x12.agent.AgentUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATREQUEST']._serialized_start=22
  _globals['_CHATREQUEST']._serialized_end=66
  _globals['_CHATRESPONSE']._serialized_start=68
  _globals['_CHATRESPONSE']._serialized_end=97
  _globals['_AGENTREQUEST']._serialized_start=99
  _globals['_AGENTREQUEST']._serialized_end=143
  _globals['_AGENTRESPONSE']._serialized_start=145
  _globals['_AGENTRESPONSE']._serialized_end=196
  _globals['_LOGLINE']._serialized_start=198
  _globals['_LOGLINE']._serialized_end=221
  _globals['_LOGREQUEST']._serialized_start=223
  _globals['_LOGREQUEST']._serialized_end=252
  _globals['_WORKFLOWREQUEST']._serialized_start=254
  _globals['_WORKFLOWREQUEST']._serialized_end=304
  _globals['_AGENTUPDATE']._serialized_start=307
  _globals['_AGENTUPDATE']._serialized_end=481
  _globals['_LOGENTRY']._serialized_start=483
  _globals['_LOGENTRY']._serialized_end=549
  _globals['_WORKFLOWEVENT']._serialized_start=551
  _globals['_WORKFLOWEVENT']._serialized_end=602
  _globals['_FINALANSWER']._serialized_start=604
  _globals['_FINALANSWER']._serialized_end=634
  _globals['_WORKFLOWITEM']._serialized_start=636
  _globals['_WORKFLOWITEM']._serialized_end=679
  _globals['_WORKFLOWLIST']._serialized_start=681
  _globals['_WORKFLOWLIST']._serialized_end=731
  _globals['_CHATSERVICE']._serialized_start=733
  _globals['_CHATSERVICE']._serialized_end=810
  _globals['_AGENTSERVICE']._serialized_start=813
  _globals['_AGENTSERVICE']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
