version: '3.9'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    ports:
      - "80:80"       # HTTP
      - "443:443"     # HTTPS
      - "8081:8081"   # Dashboard
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic.yml
      - ./certs:/certs
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--log.level=DEBUG"
      - "--certificatesResolvers.devresolver.acme.tlsChallenge=true"
      - "--certificatesResolvers.devresolver.acme.email=dev@example.com"
      - "--certificatesResolvers.devresolver.acme.storage=/certs/acme.json"